apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
  namespace: redis-new
  labels:
    app: redis-cluster
spec:
  selector:
    app: redis-cluster
    appCluster: redis-cluster
  ports:
  - name: redis-cluster
    port: 7379
  clusterIP: None
